/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyotyrant_RDBQRY */

#ifndef _Included_tokyotyrant_RDBQRY
#define _Included_tokyotyrant_RDBQRY
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyotyrant_RDBQRY_QCSTREQ
#define tokyotyrant_RDBQRY_QCSTREQ 0L
#undef tokyotyrant_RDBQRY_QCSTRINC
#define tokyotyrant_RDBQRY_QCSTRINC 1L
#undef tokyotyrant_RDBQRY_QCSTRBW
#define tokyotyrant_RDBQRY_QCSTRBW 2L
#undef tokyotyrant_RDBQRY_QCSTREW
#define tokyotyrant_RDBQRY_QCSTREW 3L
#undef tokyotyrant_RDBQRY_QCSTRAND
#define tokyotyrant_RDBQRY_QCSTRAND 4L
#undef tokyotyrant_RDBQRY_QCSTROR
#define tokyotyrant_RDBQRY_QCSTROR 5L
#undef tokyotyrant_RDBQRY_QCSTROREQ
#define tokyotyrant_RDBQRY_QCSTROREQ 6L
#undef tokyotyrant_RDBQRY_QCSTRRX
#define tokyotyrant_RDBQRY_QCSTRRX 7L
#undef tokyotyrant_RDBQRY_QCNUMEQ
#define tokyotyrant_RDBQRY_QCNUMEQ 8L
#undef tokyotyrant_RDBQRY_QCNUMGT
#define tokyotyrant_RDBQRY_QCNUMGT 9L
#undef tokyotyrant_RDBQRY_QCNUMGE
#define tokyotyrant_RDBQRY_QCNUMGE 10L
#undef tokyotyrant_RDBQRY_QCNUMLT
#define tokyotyrant_RDBQRY_QCNUMLT 11L
#undef tokyotyrant_RDBQRY_QCNUMLE
#define tokyotyrant_RDBQRY_QCNUMLE 12L
#undef tokyotyrant_RDBQRY_QCNUMBT
#define tokyotyrant_RDBQRY_QCNUMBT 13L
#undef tokyotyrant_RDBQRY_QCNUMOREQ
#define tokyotyrant_RDBQRY_QCNUMOREQ 14L
#undef tokyotyrant_RDBQRY_QCFTSPH
#define tokyotyrant_RDBQRY_QCFTSPH 15L
#undef tokyotyrant_RDBQRY_QCFTSAND
#define tokyotyrant_RDBQRY_QCFTSAND 16L
#undef tokyotyrant_RDBQRY_QCFTSOR
#define tokyotyrant_RDBQRY_QCFTSOR 17L
#undef tokyotyrant_RDBQRY_QCFTSEX
#define tokyotyrant_RDBQRY_QCFTSEX 18L
#undef tokyotyrant_RDBQRY_QCNEGATE
#define tokyotyrant_RDBQRY_QCNEGATE 16777216L
#undef tokyotyrant_RDBQRY_QCNOIDX
#define tokyotyrant_RDBQRY_QCNOIDX 33554432L
#undef tokyotyrant_RDBQRY_QOSTRASC
#define tokyotyrant_RDBQRY_QOSTRASC 0L
#undef tokyotyrant_RDBQRY_QOSTRDESC
#define tokyotyrant_RDBQRY_QOSTRDESC 1L
#undef tokyotyrant_RDBQRY_QONUMASC
#define tokyotyrant_RDBQRY_QONUMASC 2L
#undef tokyotyrant_RDBQRY_QONUMDESC
#define tokyotyrant_RDBQRY_QONUMDESC 3L
#undef tokyotyrant_RDBQRY_MSUNION
#define tokyotyrant_RDBQRY_MSUNION 0L
#undef tokyotyrant_RDBQRY_MSISECT
#define tokyotyrant_RDBQRY_MSISECT 1L
#undef tokyotyrant_RDBQRY_MSDIFF
#define tokyotyrant_RDBQRY_MSDIFF 2L

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    addcond
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_addcond
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    setorder
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_setorder
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    setlimit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_setlimit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    search
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyotyrant_RDBQRY_search
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    searchout
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_RDBQRY_searchout
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    hint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyotyrant_RDBQRY_hint
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    metasearch
 * Signature: ([Ltokyotyrant/RDBQRY;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyotyrant_RDBQRY_metasearch
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    initialize
 * Signature: (Ltokyotyrant/TDB;)V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tokyotyrant_RDBQRY
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_RDBQRY_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
