/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tokyotyrant_TCRDB */

#ifndef _Included_tokyotyrant_TCRDB
#define _Included_tokyotyrant_TCRDB
#ifdef __cplusplus
extern "C" {
#endif
#undef tokyotyrant_TCRDB_ESUCCESS
#define tokyotyrant_TCRDB_ESUCCESS 0L
#undef tokyotyrant_TCRDB_ETHREAD
#define tokyotyrant_TCRDB_ETHREAD 1L
#undef tokyotyrant_TCRDB_EINVALID
#define tokyotyrant_TCRDB_EINVALID 2L
#undef tokyotyrant_TCRDB_ENOFILE
#define tokyotyrant_TCRDB_ENOFILE 3L
#undef tokyotyrant_TCRDB_ENOPERM
#define tokyotyrant_TCRDB_ENOPERM 4L
#undef tokyotyrant_TCRDB_EMETA
#define tokyotyrant_TCRDB_EMETA 5L
#undef tokyotyrant_TCRDB_ERHEAD
#define tokyotyrant_TCRDB_ERHEAD 6L
#undef tokyotyrant_TCRDB_EOPEN
#define tokyotyrant_TCRDB_EOPEN 7L
#undef tokyotyrant_TCRDB_ECLOSE
#define tokyotyrant_TCRDB_ECLOSE 8L
#undef tokyotyrant_TCRDB_ETRUNC
#define tokyotyrant_TCRDB_ETRUNC 9L
#undef tokyotyrant_TCRDB_ESYNC
#define tokyotyrant_TCRDB_ESYNC 10L
#undef tokyotyrant_TCRDB_ESTAT
#define tokyotyrant_TCRDB_ESTAT 11L
#undef tokyotyrant_TCRDB_ESEEK
#define tokyotyrant_TCRDB_ESEEK 12L
#undef tokyotyrant_TCRDB_EREAD
#define tokyotyrant_TCRDB_EREAD 13L
#undef tokyotyrant_TCRDB_EWRITE
#define tokyotyrant_TCRDB_EWRITE 14L
#undef tokyotyrant_TCRDB_EMMAP
#define tokyotyrant_TCRDB_EMMAP 15L
#undef tokyotyrant_TCRDB_ELOCK
#define tokyotyrant_TCRDB_ELOCK 16L
#undef tokyotyrant_TCRDB_EUNLINK
#define tokyotyrant_TCRDB_EUNLINK 17L
#undef tokyotyrant_TCRDB_ERENAME
#define tokyotyrant_TCRDB_ERENAME 18L
#undef tokyotyrant_TCRDB_EMKDIR
#define tokyotyrant_TCRDB_EMKDIR 19L
#undef tokyotyrant_TCRDB_ERMDIR
#define tokyotyrant_TCRDB_ERMDIR 20L
#undef tokyotyrant_TCRDB_EKEEP
#define tokyotyrant_TCRDB_EKEEP 21L
#undef tokyotyrant_TCRDB_ENOREC
#define tokyotyrant_TCRDB_ENOREC 22L
#undef tokyotyrant_TCRDB_EMISC
#define tokyotyrant_TCRDB_EMISC 9999L
#undef tokyotyrant_TCRDB_TLARGE
#define tokyotyrant_TCRDB_TLARGE 1L
#undef tokyotyrant_TCRDB_TDEFLATE
#define tokyotyrant_TCRDB_TDEFLATE 2L
#undef tokyotyrant_TCRDB_TBZIP
#define tokyotyrant_TCRDB_TBZIP 4L
#undef tokyotyrant_TCRDB_TTCBS
#define tokyotyrant_TCRDB_TTCBS 8L
#undef tokyotyrant_TCRDB_OREADER
#define tokyotyrant_TCRDB_OREADER 1L
#undef tokyotyrant_TCRDB_OWRITER
#define tokyotyrant_TCRDB_OWRITER 2L
#undef tokyotyrant_TCRDB_OCREAT
#define tokyotyrant_TCRDB_OCREAT 4L
#undef tokyotyrant_TCRDB_OTRUNC
#define tokyotyrant_TCRDB_OTRUNC 8L
#undef tokyotyrant_TCRDB_ONOLCK
#define tokyotyrant_TCRDB_ONOLCK 16L
#undef tokyotyrant_TCRDB_OLCKNB
#define tokyotyrant_TCRDB_OLCKNB 32L
#undef tokyotyrant_TCRDB_OTSYNC
#define tokyotyrant_TCRDB_OTSYNC 64L
#undef tokyotyrant_TCRDB_ITLEXICAL
#define tokyotyrant_TCRDB_ITLEXICAL 0L
#undef tokyotyrant_TCRDB_ITDECIMAL
#define tokyotyrant_TCRDB_ITDECIMAL 1L
#undef tokyotyrant_TCRDB_ITTOKEN
#define tokyotyrant_TCRDB_ITTOKEN 2L
#undef tokyotyrant_TCRDB_ITQGRAM
#define tokyotyrant_TCRDB_ITQGRAM 3L
#undef tokyotyrant_TCRDB_ITOPT
#define tokyotyrant_TCRDB_ITOPT 9998L
#undef tokyotyrant_TCRDB_ITVOID
#define tokyotyrant_TCRDB_ITVOID 9999L
#undef tokyotyrant_TCRDB_ITKEEP
#define tokyotyrant_TCRDB_ITKEEP 16777216L
/*
 * Class:     tokyotyrant_TCRDB
 * Method:    errmsg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyotyrant_TCRDB_errmsg
  (JNIEnv *, jclass, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_TCRDB_init
  (JNIEnv *, jclass);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    ecode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tokyotyrant_TCRDB_ecode
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    tune
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_tune
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    open
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_close
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    out
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_out
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    vsiz
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_tokyotyrant_TCRDB_vsiz
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    iterinit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_iterinit
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    iternext
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tokyotyrant_TCRDB_iternext
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    fwmkeys
 * Signature: ([BI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tokyotyrant_TCRDB_fwmkeys
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    addint
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_tokyotyrant_TCRDB_addint
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    adddouble
 * Signature: ([BD)D
 */
JNIEXPORT jdouble JNICALL Java_tokyotyrant_TCRDB_adddouble
  (JNIEnv *, jobject, jbyteArray, jdouble);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    sync
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_sync
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    optimize
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_optimize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    vanish
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_vanish
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    copy
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_copy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tokyotyrant_TCRDB_path
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    rnum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyotyrant_TCRDB_rnum
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    fsiz
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyotyrant_TCRDB_dbsize
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    setindex
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_setindex
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    genuid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tokyotyrant_TCRDB_genuid
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_TCRDB_initialize
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tokyotyrant_TCRDB_destruct
  (JNIEnv *, jobject);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    putimpl
 * Signature: ([B[[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_tokyotyrant_TCRDB_putimpl
  (JNIEnv *, jobject, jbyteArray, jobjectArray, jint);

/*
 * Class:     tokyotyrant_TCRDB
 * Method:    getimpl
 * Signature: ([B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_tokyotyrant_TCRDB_getimpl
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
